In [1]:
import numpy as np
import scipy as sc
import pandas as pd
import itertools as it
import subprocess as sp
import sys
import re
import collections
import json
import pysam
import enum
import bisect

import colorlog

import pgenlib as pg

In [2]:
import matplotlib
matplotlib.use('agg')
from matplotlib import pyplot as plt

In [3]:
sys.path.append('./')

In [4]:
from Position import Position
from FastaFile import FastaFile
from BimFile import BimFile
from Read import Read

In [5]:
bamfile_name = './data/rel3.chr20.12500.10k.head.bam'

In [6]:
fasta = FastaFile('./data/chr', fast_ext='fa')
bim = BimFile('./data/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes-pgen.bim')
bamfile = pysam.AlignmentFile(filename = bamfile_name, mode = 'rb')

In [7]:
x = bamfile.next()

In [8]:
r = Read(x, fasta)

In [9]:
# name, chr, start, end, MAPQ
r.query_name, r.reference_name, r.l.get_pos(), r.r.get_pos(), r.mapping_quality

('33ecb953-edd6-445b-87da-85c4551d8c8c_Basecall_Alignment_template',
 'chr20',
 59980,
 65177,
 60)

In [16]:
# corresponding id interval (on bim file) is
read_bim_l, read_bim_r = bim.find_index_interval(query_l = r.l, query_r = r.r)

In [17]:
# Get polymorphic SNP positions (written on bim)
read_snp_pos = bim.get_bp(r.chr)[read_bim_l : read_bim_r]

In [18]:
r.get_mismatches_polymorphic(read_snp_pos)

[Mismatch(reference_position=63798, reference=<Nucleotide.C: 1>, read=<Nucleotide.T: 3>, quality=15)]

In [21]:
bim.find_index_list([Position(r.chr, ref_pos) for ref_pos 
                     in r.get_mismatches_polymorphic_pos(read_snp_pos)])

array([92])

In [22]:
bim.get_allele_1(r.chr)[92], bim.get_allele_2(r.chr)[92]

('T', 'C')

In [9]:
read_l = Position(read.reference_name, read.reference_start)
read_r = Position(read.reference_name, read.reference_end)

In [25]:
read_l.get_chrom()

'20'

In [24]:
# name, chr, start, end, MAPQ
read.query_name, read.reference_name, read_l.get_pos(), read_r.get_pos(), read.mapq

('33ecb953-edd6-445b-87da-85c4551d8c8c_Basecall_Alignment_template',
 'chr20',
 59980,
 65177,
 60)

In [11]:
# corresponding id interval (on bim file) is
read_bim_l, read_bim_r = bim.find_index_interval(query_l = read_l, query_r = read_r)
read_bim_l, read_bim_r

(0, 134)

In [12]:
# Get polymorphic SNP positions (written on bim)
read_snp_pos = bim.get_bp(read_l.get_chrom())[read_bim_l : read_bim_r]

In [13]:
r = Read(read, fasta.get_seq(read_l.get_chrom()))

In [14]:
r.get_mismatches()

[Mismatch(reference_position=60992, reference=<Nucleotide.G: 2>, read=<Nucleotide.T: 3>, quality=14),
 Mismatch(reference_position=61171, reference=<Nucleotide.A: 0>, read=<Nucleotide.T: 3>, quality=14),
 Mismatch(reference_position=61220, reference=<Nucleotide.G: 2>, read=<Nucleotide.A: 0>, quality=17),
 Mismatch(reference_position=63344, reference=<Nucleotide.T: 3>, read=<Nucleotide.A: 0>, quality=15),
 Mismatch(reference_position=63377, reference=<Nucleotide.C: 1>, read=<Nucleotide.A: 0>, quality=16),
 Mismatch(reference_position=63378, reference=<Nucleotide.C: 1>, read=<Nucleotide.A: 0>, quality=16),
 Mismatch(reference_position=63798, reference=<Nucleotide.C: 1>, read=<Nucleotide.T: 3>, quality=15)]

In [15]:
r.get_mismatches_pos()

array([60992, 61171, 61220, 63344, 63377, 63378, 63798])

In [16]:
r.get_mismatches_polymorphic(read_snp_pos)

[Mismatch(reference_position=63798, reference=<Nucleotide.C: 1>, read=<Nucleotide.T: 3>, quality=15)]

In [17]:
r.get_mismatches_polymorphic_pos(read_snp_pos)

array([63798])

In [15]:
bim.find_index(Position(20, 63798))

92

In [20]:
bim.get_allele_1(chromosome=20)[92], bim.get_allele_2(chromosome=20)[92]

('T', 'C')

In [22]:
from Nucleotide import Nucleotide

In [23]:
Nucleotide['T']

<Nucleotide.T: 3>

In [64]:
#read.seq

In [11]:
bim.find_index(query=Position(20, 60000))

0

In [12]:
ref = fasta.get_seq(20)

In [13]:
type(ref)

pysam.libcfaidx.FastaFile

In [7]:
bim.raw_tables.keys()

['20']

In [8]:
bim.is_loaded(20)

True

In [9]:
bim.is_loaded('20')

True